INSERT INTO category (name, type) values
('PAYCHECK', 'INCOME'),
('BONUS', 'INCOME'),
('GIFT', 'INCOME'),
('SELLING', 'INCOME'),
('OTHER_INCOME', 'INCOME');

INSERT INTO category (name, type) values
('GROCERIES', 'EXPENSE'),
('RESTAURANTS', 'EXPENSE'),
('TAKEAWAY', 'EXPENSE'),
('COFFEE', 'EXPENSE'),
('CATERING', 'EXPENSE'),
('DROGERIE', 'EXPENSE'),
('MEDICAL', 'EXPENSE'),
('CLOTHES', 'EXPENSE'),
('APARTMENT', 'EXPENSE'),
('TRANSPORT', 'EXPENSE'),
('SUBSCRIPTIONS', 'EXPENSE'),
('PLEASURES', 'EXPENSE'),
('TOYS', 'EXPENSE'),
('TRAVELING', 'EXPENSE'),
('BILLS', 'EXPENSE'),
('OTHER_EXPENSE', 'EXPENSE'),
('INVESTING', 'EXPENSE');